<?php

namespace App\Support;

/**
 * Data referensi wilayah administratif Indonesia: provinsi dan kabupaten/kota.
 *
 * SUMBER: `database/data/wilayah_indonesia.sql` (kode BPS), disediakan pemilik
 * proyek. Dipakai sebagai daftar pilihan `daerah_asal` transmigran, yaitu
 * kabupaten/kota tempat keluarga berasal sebelum mengikuti program.
 *
 * BUKAN data contoh, melainkan data referensi yang akan tetap dipakai setelah
 * backend berdiri. Karena itu ia berdiri sendiri, terpisah dari `DummyData`
 * yang berisi simulasi transaksi.
 *
 * Kode mengikuti BPS, dan hierarkinya terbaca dari kodenya sendiri: dua digit
 * pertama kabupaten adalah kode provinsinya. Kabupaten Malaka bernilai 5321,
 * cocok dengan empat digit pertama NIK pada data contoh (5321011505800001).
 *
 * NAMA DISIMPAN APA ADANYA beserta awalan Kabupaten atau Kota. Awalan itu bukan
 * hiasan: nama kabupaten TIDAK unik secara nasional, dan Kabupaten Kupang (5301)
 * berbeda dari Kota Kupang (5371). Menanggalkan awalannya membuat keduanya
 * tampak sebagai satu tempat yang sama.
 *
 * Berbeda dari isian pengguna, nama di sini TIDAK dihuruf-besarkan
 * `UppercaseInput`: ia data master, sepola dengan nama satuan permukiman
 * yang juga ditulis `SP Kapitan Meo`.
 *
 * KECAMATAN DAN DESA SENGAJA TIDAK DIMUAT di sini. Berkas sumber memuat 7.000
 * kecamatan dan 83.000 kelurahan, sedangkan komponen pilih-cari menyematkan
 * seluruh opsi ke dalam HTML. Keduanya menunggu Tahap 3 ketika pemuatan
 * bertahap lewat endpoint sudah tersedia. Kecamatan dan desa LOKUS tetap pada
 * `DummyData::wilayah()` sebab hanya wilayah ber-SP yang bermakna di sana.
 */
class DataWilayah
{
    /**
     * Daftar provinsi.
     *
     * @return array<int, array{id: int, kode: string, nama: string}>
     */
    public static function provinsi(): array
    {
        return [
            ['id' => 11, 'kode' => '11', 'nama' => 'Aceh'],
            ['id' => 12, 'kode' => '12', 'nama' => 'Sumatera Utara'],
            ['id' => 13, 'kode' => '13', 'nama' => 'Sumatera Barat'],
            ['id' => 14, 'kode' => '14', 'nama' => 'Riau'],
            ['id' => 15, 'kode' => '15', 'nama' => 'Jambi'],
            ['id' => 16, 'kode' => '16', 'nama' => 'Sumatera Selatan'],
            ['id' => 17, 'kode' => '17', 'nama' => 'Bengkulu'],
            ['id' => 18, 'kode' => '18', 'nama' => 'Lampung'],
            ['id' => 19, 'kode' => '19', 'nama' => 'Kepulauan Bangka Belitung'],
            ['id' => 21, 'kode' => '21', 'nama' => 'Kepulauan Riau'],
            ['id' => 31, 'kode' => '31', 'nama' => 'Daerah Khusus Ibukota Jakarta'],
            ['id' => 32, 'kode' => '32', 'nama' => 'Jawa Barat'],
            ['id' => 33, 'kode' => '33', 'nama' => 'Jawa Tengah'],
            ['id' => 34, 'kode' => '34', 'nama' => 'Daerah Istimewa Yogyakarta'],
            ['id' => 35, 'kode' => '35', 'nama' => 'Jawa Timur'],
            ['id' => 36, 'kode' => '36', 'nama' => 'Banten'],
            ['id' => 51, 'kode' => '51', 'nama' => 'Bali'],
            ['id' => 52, 'kode' => '52', 'nama' => 'Nusa Tenggara Barat'],
            ['id' => 53, 'kode' => '53', 'nama' => 'Nusa Tenggara Timur'],
            ['id' => 61, 'kode' => '61', 'nama' => 'Kalimantan Barat'],
            ['id' => 62, 'kode' => '62', 'nama' => 'Kalimantan Tengah'],
            ['id' => 63, 'kode' => '63', 'nama' => 'Kalimantan Selatan'],
            ['id' => 64, 'kode' => '64', 'nama' => 'Kalimantan Timur'],
            ['id' => 65, 'kode' => '65', 'nama' => 'Kalimantan Utara'],
            ['id' => 71, 'kode' => '71', 'nama' => 'Sulawesi Utara'],
            ['id' => 72, 'kode' => '72', 'nama' => 'Sulawesi Tengah'],
            ['id' => 73, 'kode' => '73', 'nama' => 'Sulawesi Selatan'],
            ['id' => 74, 'kode' => '74', 'nama' => 'Sulawesi Tenggara'],
            ['id' => 75, 'kode' => '75', 'nama' => 'Gorontalo'],
            ['id' => 76, 'kode' => '76', 'nama' => 'Sulawesi Barat'],
            ['id' => 81, 'kode' => '81', 'nama' => 'Maluku'],
            ['id' => 82, 'kode' => '82', 'nama' => 'Maluku Utara'],
            ['id' => 91, 'kode' => '91', 'nama' => 'Papua'],
            ['id' => 92, 'kode' => '92', 'nama' => 'Papua Barat'],
            ['id' => 93, 'kode' => '93', 'nama' => 'Papua Selatan'],
            ['id' => 94, 'kode' => '94', 'nama' => 'Papua Tengah'],
            ['id' => 95, 'kode' => '95', 'nama' => 'Papua Pegunungan'],
            ['id' => 96, 'kode' => '96', 'nama' => 'Papua Barat Daya'],
        ];
    }

    /**
     * Daftar kabupaten dan kota.
     *
     * `provinsi_id` diturunkan dari dua digit pertama kodenya, sehingga tidak
     * dapat berselisih dengan kodenya sendiri.
     *
     * @return array<int, array{id: int, kode: string, provinsi_id: int, nama: string}>
     */
    public static function kabupaten(): array
    {
        return [
            ['id' => 1101, 'kode' => '1101', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Selatan'],
            ['id' => 1102, 'kode' => '1102', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Tenggara'],
            ['id' => 1103, 'kode' => '1103', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Timur'],
            ['id' => 1104, 'kode' => '1104', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Tengah'],
            ['id' => 1105, 'kode' => '1105', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Barat'],
            ['id' => 1106, 'kode' => '1106', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Besar'],
            ['id' => 1107, 'kode' => '1107', 'provinsi_id' => 11, 'nama' => 'Kabupaten Pidie'],
            ['id' => 1108, 'kode' => '1108', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Utara'],
            ['id' => 1109, 'kode' => '1109', 'provinsi_id' => 11, 'nama' => 'Kabupaten Simeulue'],
            ['id' => 1110, 'kode' => '1110', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Singkil'],
            ['id' => 1111, 'kode' => '1111', 'provinsi_id' => 11, 'nama' => 'Kabupaten Bireuen'],
            ['id' => 1112, 'kode' => '1112', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Barat Daya'],
            ['id' => 1113, 'kode' => '1113', 'provinsi_id' => 11, 'nama' => 'Kabupaten Gayo Lues'],
            ['id' => 1114, 'kode' => '1114', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Jaya'],
            ['id' => 1115, 'kode' => '1115', 'provinsi_id' => 11, 'nama' => 'Kabupaten Nagan Raya'],
            ['id' => 1116, 'kode' => '1116', 'provinsi_id' => 11, 'nama' => 'Kabupaten Aceh Tamiang'],
            ['id' => 1117, 'kode' => '1117', 'provinsi_id' => 11, 'nama' => 'Kabupaten Bener Meriah'],
            ['id' => 1118, 'kode' => '1118', 'provinsi_id' => 11, 'nama' => 'Kabupaten Pidie Jaya'],
            ['id' => 1171, 'kode' => '1171', 'provinsi_id' => 11, 'nama' => 'Kota Banda Aceh'],
            ['id' => 1172, 'kode' => '1172', 'provinsi_id' => 11, 'nama' => 'Kota Sabang'],
            ['id' => 1173, 'kode' => '1173', 'provinsi_id' => 11, 'nama' => 'Kota Lhokseumawe'],
            ['id' => 1174, 'kode' => '1174', 'provinsi_id' => 11, 'nama' => 'Kota Langsa'],
            ['id' => 1175, 'kode' => '1175', 'provinsi_id' => 11, 'nama' => 'Kota Subulussalam'],
            ['id' => 1201, 'kode' => '1201', 'provinsi_id' => 12, 'nama' => 'Kabupaten Tapanuli Tengah'],
            ['id' => 1202, 'kode' => '1202', 'provinsi_id' => 12, 'nama' => 'Kabupaten Tapanuli Utara'],
            ['id' => 1203, 'kode' => '1203', 'provinsi_id' => 12, 'nama' => 'Kabupaten Tapanuli Selatan'],
            ['id' => 1204, 'kode' => '1204', 'provinsi_id' => 12, 'nama' => 'Kabupaten Nias'],
            ['id' => 1205, 'kode' => '1205', 'provinsi_id' => 12, 'nama' => 'Kabupaten Langkat'],
            ['id' => 1206, 'kode' => '1206', 'provinsi_id' => 12, 'nama' => 'Kabupaten Karo'],
            ['id' => 1207, 'kode' => '1207', 'provinsi_id' => 12, 'nama' => 'Kabupaten Deli Serdang'],
            ['id' => 1208, 'kode' => '1208', 'provinsi_id' => 12, 'nama' => 'Kabupaten Simalungun'],
            ['id' => 1209, 'kode' => '1209', 'provinsi_id' => 12, 'nama' => 'Kabupaten Asahan'],
            ['id' => 1210, 'kode' => '1210', 'provinsi_id' => 12, 'nama' => 'Kabupaten Labuhanbatu'],
            ['id' => 1211, 'kode' => '1211', 'provinsi_id' => 12, 'nama' => 'Kabupaten Dairi'],
            ['id' => 1212, 'kode' => '1212', 'provinsi_id' => 12, 'nama' => 'Kabupaten Toba'],
            ['id' => 1213, 'kode' => '1213', 'provinsi_id' => 12, 'nama' => 'Kabupaten Mandailing Natal'],
            ['id' => 1214, 'kode' => '1214', 'provinsi_id' => 12, 'nama' => 'Kabupaten Nias Selatan'],
            ['id' => 1215, 'kode' => '1215', 'provinsi_id' => 12, 'nama' => 'Kabupaten Pakpak Bharat'],
            ['id' => 1216, 'kode' => '1216', 'provinsi_id' => 12, 'nama' => 'Kabupaten Humbang Hasundutan'],
            ['id' => 1217, 'kode' => '1217', 'provinsi_id' => 12, 'nama' => 'Kabupaten Samosir'],
            ['id' => 1218, 'kode' => '1218', 'provinsi_id' => 12, 'nama' => 'Kabupaten Serdang Bedagai'],
            ['id' => 1219, 'kode' => '1219', 'provinsi_id' => 12, 'nama' => 'Kabupaten Batu Bara'],
            ['id' => 1220, 'kode' => '1220', 'provinsi_id' => 12, 'nama' => 'Kabupaten Padang Lawas Utara'],
            ['id' => 1221, 'kode' => '1221', 'provinsi_id' => 12, 'nama' => 'Kabupaten Padang Lawas'],
            ['id' => 1222, 'kode' => '1222', 'provinsi_id' => 12, 'nama' => 'Kabupaten Labuhanbatu Selatan'],
            ['id' => 1223, 'kode' => '1223', 'provinsi_id' => 12, 'nama' => 'Kabupaten Labuhanbatu Utara'],
            ['id' => 1224, 'kode' => '1224', 'provinsi_id' => 12, 'nama' => 'Kabupaten Nias Utara'],
            ['id' => 1225, 'kode' => '1225', 'provinsi_id' => 12, 'nama' => 'Kabupaten Nias Barat'],
            ['id' => 1271, 'kode' => '1271', 'provinsi_id' => 12, 'nama' => 'Kota Medan'],
            ['id' => 1272, 'kode' => '1272', 'provinsi_id' => 12, 'nama' => 'Kota Pematangsiantar'],
            ['id' => 1273, 'kode' => '1273', 'provinsi_id' => 12, 'nama' => 'Kota Sibolga'],
            ['id' => 1274, 'kode' => '1274', 'provinsi_id' => 12, 'nama' => 'Kota Tanjungbalai'],
            ['id' => 1275, 'kode' => '1275', 'provinsi_id' => 12, 'nama' => 'Kota Binjai'],
            ['id' => 1276, 'kode' => '1276', 'provinsi_id' => 12, 'nama' => 'Kota Tebing Tinggi'],
            ['id' => 1277, 'kode' => '1277', 'provinsi_id' => 12, 'nama' => 'Kota Padangsidimpuan'],
            ['id' => 1278, 'kode' => '1278', 'provinsi_id' => 12, 'nama' => 'Kota Gunungsitoli'],
            ['id' => 1301, 'kode' => '1301', 'provinsi_id' => 13, 'nama' => 'Kabupaten Pesisir Selatan'],
            ['id' => 1302, 'kode' => '1302', 'provinsi_id' => 13, 'nama' => 'Kabupaten Solok'],
            ['id' => 1303, 'kode' => '1303', 'provinsi_id' => 13, 'nama' => 'Kabupaten Sijunjung'],
            ['id' => 1304, 'kode' => '1304', 'provinsi_id' => 13, 'nama' => 'Kabupaten Tanah Datar'],
            ['id' => 1305, 'kode' => '1305', 'provinsi_id' => 13, 'nama' => 'Kabupaten Padang Pariaman'],
            ['id' => 1306, 'kode' => '1306', 'provinsi_id' => 13, 'nama' => 'Kabupaten Agam'],
            ['id' => 1307, 'kode' => '1307', 'provinsi_id' => 13, 'nama' => 'Kabupaten Lima Puluh Kota'],
            ['id' => 1308, 'kode' => '1308', 'provinsi_id' => 13, 'nama' => 'Kabupaten Pasaman'],
            ['id' => 1309, 'kode' => '1309', 'provinsi_id' => 13, 'nama' => 'Kabupaten Kepulauan Mentawai'],
            ['id' => 1310, 'kode' => '1310', 'provinsi_id' => 13, 'nama' => 'Kabupaten Dharmasraya'],
            ['id' => 1311, 'kode' => '1311', 'provinsi_id' => 13, 'nama' => 'Kabupaten Solok Selatan'],
            ['id' => 1312, 'kode' => '1312', 'provinsi_id' => 13, 'nama' => 'Kabupaten Pasaman Barat'],
            ['id' => 1371, 'kode' => '1371', 'provinsi_id' => 13, 'nama' => 'Kota Padang'],
            ['id' => 1372, 'kode' => '1372', 'provinsi_id' => 13, 'nama' => 'Kota Solok'],
            ['id' => 1373, 'kode' => '1373', 'provinsi_id' => 13, 'nama' => 'Kota Sawahlunto'],
            ['id' => 1374, 'kode' => '1374', 'provinsi_id' => 13, 'nama' => 'Kota Padang Panjang'],
            ['id' => 1375, 'kode' => '1375', 'provinsi_id' => 13, 'nama' => 'Kota Bukittinggi'],
            ['id' => 1376, 'kode' => '1376', 'provinsi_id' => 13, 'nama' => 'Kota Payakumbuh'],
            ['id' => 1377, 'kode' => '1377', 'provinsi_id' => 13, 'nama' => 'Kota Pariaman'],
            ['id' => 1401, 'kode' => '1401', 'provinsi_id' => 14, 'nama' => 'Kabupaten Kampar'],
            ['id' => 1402, 'kode' => '1402', 'provinsi_id' => 14, 'nama' => 'Kabupaten Indragiri Hulu'],
            ['id' => 1403, 'kode' => '1403', 'provinsi_id' => 14, 'nama' => 'Kabupaten Bengkalis'],
            ['id' => 1404, 'kode' => '1404', 'provinsi_id' => 14, 'nama' => 'Kabupaten Indragiri Hilir'],
            ['id' => 1405, 'kode' => '1405', 'provinsi_id' => 14, 'nama' => 'Kabupaten Pelalawan'],
            ['id' => 1406, 'kode' => '1406', 'provinsi_id' => 14, 'nama' => 'Kabupaten Rokan Hulu'],
            ['id' => 1407, 'kode' => '1407', 'provinsi_id' => 14, 'nama' => 'Kabupaten Rokan Hilir'],
            ['id' => 1408, 'kode' => '1408', 'provinsi_id' => 14, 'nama' => 'Kabupaten Siak'],
            ['id' => 1409, 'kode' => '1409', 'provinsi_id' => 14, 'nama' => 'Kabupaten Kuantan Singingi'],
            ['id' => 1410, 'kode' => '1410', 'provinsi_id' => 14, 'nama' => 'Kabupaten Kepulauan Meranti'],
            ['id' => 1471, 'kode' => '1471', 'provinsi_id' => 14, 'nama' => 'Kota Pekanbaru'],
            ['id' => 1472, 'kode' => '1472', 'provinsi_id' => 14, 'nama' => 'Kota Dumai'],
            ['id' => 1501, 'kode' => '1501', 'provinsi_id' => 15, 'nama' => 'Kabupaten Kerinci'],
            ['id' => 1502, 'kode' => '1502', 'provinsi_id' => 15, 'nama' => 'Kabupaten Merangin'],
            ['id' => 1503, 'kode' => '1503', 'provinsi_id' => 15, 'nama' => 'Kabupaten Sarolangun'],
            ['id' => 1504, 'kode' => '1504', 'provinsi_id' => 15, 'nama' => 'Kabupaten Batanghari'],
            ['id' => 1505, 'kode' => '1505', 'provinsi_id' => 15, 'nama' => 'Kabupaten Muaro Jambi'],
            ['id' => 1506, 'kode' => '1506', 'provinsi_id' => 15, 'nama' => 'Kabupaten Tanjung Jabung Barat'],
            ['id' => 1507, 'kode' => '1507', 'provinsi_id' => 15, 'nama' => 'Kabupaten Tanjung Jabung Timur'],
            ['id' => 1508, 'kode' => '1508', 'provinsi_id' => 15, 'nama' => 'Kabupaten Bungo'],
            ['id' => 1509, 'kode' => '1509', 'provinsi_id' => 15, 'nama' => 'Kabupaten Tebo'],
            ['id' => 1571, 'kode' => '1571', 'provinsi_id' => 15, 'nama' => 'Kota Jambi'],
            ['id' => 1572, 'kode' => '1572', 'provinsi_id' => 15, 'nama' => 'Kota Sungai Penuh'],
            ['id' => 1601, 'kode' => '1601', 'provinsi_id' => 16, 'nama' => 'Kabupaten Ogan Komering Ulu'],
            ['id' => 1602, 'kode' => '1602', 'provinsi_id' => 16, 'nama' => 'Kabupaten Ogan Komering Ilir'],
            ['id' => 1603, 'kode' => '1603', 'provinsi_id' => 16, 'nama' => 'Kabupaten Muara Enim'],
            ['id' => 1604, 'kode' => '1604', 'provinsi_id' => 16, 'nama' => 'Kabupaten Lahat'],
            ['id' => 1605, 'kode' => '1605', 'provinsi_id' => 16, 'nama' => 'Kabupaten Musi Rawas'],
            ['id' => 1606, 'kode' => '1606', 'provinsi_id' => 16, 'nama' => 'Kabupaten Musi Banyuasin'],
            ['id' => 1607, 'kode' => '1607', 'provinsi_id' => 16, 'nama' => 'Kabupaten Banyuasin'],
            ['id' => 1608, 'kode' => '1608', 'provinsi_id' => 16, 'nama' => 'Kabupaten Ogan Komering Ulu Timu'],
            ['id' => 1609, 'kode' => '1609', 'provinsi_id' => 16, 'nama' => 'Kabupaten Ogan Komering Ulu Sela'],
            ['id' => 1610, 'kode' => '1610', 'provinsi_id' => 16, 'nama' => 'Kabupaten Ogan Ilir'],
            ['id' => 1611, 'kode' => '1611', 'provinsi_id' => 16, 'nama' => 'Kabupaten Empat Lawang'],
            ['id' => 1612, 'kode' => '1612', 'provinsi_id' => 16, 'nama' => 'Kabupaten Penukal Abab Lematang '],
            ['id' => 1613, 'kode' => '1613', 'provinsi_id' => 16, 'nama' => 'Kabupaten Musi Rawas Utara'],
            ['id' => 1671, 'kode' => '1671', 'provinsi_id' => 16, 'nama' => 'Kota Palembang'],
            ['id' => 1672, 'kode' => '1672', 'provinsi_id' => 16, 'nama' => 'Kota Pagar Alam'],
            ['id' => 1673, 'kode' => '1673', 'provinsi_id' => 16, 'nama' => 'Kota Lubuk Linggau'],
            ['id' => 1674, 'kode' => '1674', 'provinsi_id' => 16, 'nama' => 'Kota Prabumulih'],
            ['id' => 1701, 'kode' => '1701', 'provinsi_id' => 17, 'nama' => 'Kabupaten Bengkulu Selatan'],
            ['id' => 1702, 'kode' => '1702', 'provinsi_id' => 17, 'nama' => 'Kabupaten Rejang Lebong'],
            ['id' => 1703, 'kode' => '1703', 'provinsi_id' => 17, 'nama' => 'Kabupaten Bengkulu Utara'],
            ['id' => 1704, 'kode' => '1704', 'provinsi_id' => 17, 'nama' => 'Kabupaten Kaur'],
            ['id' => 1705, 'kode' => '1705', 'provinsi_id' => 17, 'nama' => 'Kabupaten Seluma'],
            ['id' => 1706, 'kode' => '1706', 'provinsi_id' => 17, 'nama' => 'Kabupaten Mukomuko'],
            ['id' => 1707, 'kode' => '1707', 'provinsi_id' => 17, 'nama' => 'Kabupaten Lebong'],
            ['id' => 1708, 'kode' => '1708', 'provinsi_id' => 17, 'nama' => 'Kabupaten Kepahiang'],
            ['id' => 1709, 'kode' => '1709', 'provinsi_id' => 17, 'nama' => 'Kabupaten Bengkulu Tengah'],
            ['id' => 1771, 'kode' => '1771', 'provinsi_id' => 17, 'nama' => 'Kota Bengkulu'],
            ['id' => 1801, 'kode' => '1801', 'provinsi_id' => 18, 'nama' => 'Kabupaten Lampung Selatan'],
            ['id' => 1802, 'kode' => '1802', 'provinsi_id' => 18, 'nama' => 'Kabupaten Lampung Tengah'],
            ['id' => 1803, 'kode' => '1803', 'provinsi_id' => 18, 'nama' => 'Kabupaten Lampung Utara'],
            ['id' => 1804, 'kode' => '1804', 'provinsi_id' => 18, 'nama' => 'Kabupaten Lampung Barat'],
            ['id' => 1805, 'kode' => '1805', 'provinsi_id' => 18, 'nama' => 'Kabupaten Tulang Bawang'],
            ['id' => 1806, 'kode' => '1806', 'provinsi_id' => 18, 'nama' => 'Kabupaten Tanggamus'],
            ['id' => 1807, 'kode' => '1807', 'provinsi_id' => 18, 'nama' => 'Kabupaten Lampung Timur'],
            ['id' => 1808, 'kode' => '1808', 'provinsi_id' => 18, 'nama' => 'Kabupaten Way Kanan'],
            ['id' => 1809, 'kode' => '1809', 'provinsi_id' => 18, 'nama' => 'Kabupaten Pesawaran'],
            ['id' => 1810, 'kode' => '1810', 'provinsi_id' => 18, 'nama' => 'Kabupaten Pringsewu'],
            ['id' => 1811, 'kode' => '1811', 'provinsi_id' => 18, 'nama' => 'Kabupaten Mesuji'],
            ['id' => 1812, 'kode' => '1812', 'provinsi_id' => 18, 'nama' => 'Kabupaten Tulang Bawang Barat'],
            ['id' => 1813, 'kode' => '1813', 'provinsi_id' => 18, 'nama' => 'Kabupaten Pesisir Barat'],
            ['id' => 1871, 'kode' => '1871', 'provinsi_id' => 18, 'nama' => 'Kota Bandar Lampung'],
            ['id' => 1872, 'kode' => '1872', 'provinsi_id' => 18, 'nama' => 'Kota Metro'],
            ['id' => 1901, 'kode' => '1901', 'provinsi_id' => 19, 'nama' => 'Kabupaten Bangka'],
            ['id' => 1902, 'kode' => '1902', 'provinsi_id' => 19, 'nama' => 'Kabupaten Belitung'],
            ['id' => 1903, 'kode' => '1903', 'provinsi_id' => 19, 'nama' => 'Kabupaten Bangka Selatan'],
            ['id' => 1904, 'kode' => '1904', 'provinsi_id' => 19, 'nama' => 'Kabupaten Bangka Tengah'],
            ['id' => 1905, 'kode' => '1905', 'provinsi_id' => 19, 'nama' => 'Kabupaten Bangka Barat'],
            ['id' => 1906, 'kode' => '1906', 'provinsi_id' => 19, 'nama' => 'Kabupaten Belitung Timur'],
            ['id' => 1971, 'kode' => '1971', 'provinsi_id' => 19, 'nama' => 'Kota Pangkal Pinang'],
            ['id' => 2101, 'kode' => '2101', 'provinsi_id' => 21, 'nama' => 'Kabupaten Bintan'],
            ['id' => 2102, 'kode' => '2102', 'provinsi_id' => 21, 'nama' => 'Kabupaten Karimun'],
            ['id' => 2103, 'kode' => '2103', 'provinsi_id' => 21, 'nama' => 'Kabupaten Natuna'],
            ['id' => 2104, 'kode' => '2104', 'provinsi_id' => 21, 'nama' => 'Kabupaten Lingga'],
            ['id' => 2105, 'kode' => '2105', 'provinsi_id' => 21, 'nama' => 'Kabupaten Kepulauan Anambas'],
            ['id' => 2171, 'kode' => '2171', 'provinsi_id' => 21, 'nama' => 'Kota Batam'],
            ['id' => 2172, 'kode' => '2172', 'provinsi_id' => 21, 'nama' => 'Kota Tanjung Pinang'],
            ['id' => 3101, 'kode' => '3101', 'provinsi_id' => 31, 'nama' => 'Kabupaten Administrasi Kepulauan'],
            ['id' => 3171, 'kode' => '3171', 'provinsi_id' => 31, 'nama' => 'Kota Administrasi Jakarta Pusat'],
            ['id' => 3172, 'kode' => '3172', 'provinsi_id' => 31, 'nama' => 'Kota Administrasi Jakarta Utara '],
            ['id' => 3173, 'kode' => '3173', 'provinsi_id' => 31, 'nama' => 'Kota Administrasi Jakarta Barat'],
            ['id' => 3174, 'kode' => '3174', 'provinsi_id' => 31, 'nama' => 'Kota Administrasi Jakarta Selata'],
            ['id' => 3175, 'kode' => '3175', 'provinsi_id' => 31, 'nama' => 'Kota Administrasi Jakarta Timur'],
            ['id' => 3201, 'kode' => '3201', 'provinsi_id' => 32, 'nama' => 'Kabupaten Bogor'],
            ['id' => 3202, 'kode' => '3202', 'provinsi_id' => 32, 'nama' => 'Kabupaten Sukabumi'],
            ['id' => 3203, 'kode' => '3203', 'provinsi_id' => 32, 'nama' => 'Kabupaten Cianjur'],
            ['id' => 3204, 'kode' => '3204', 'provinsi_id' => 32, 'nama' => 'Kabupaten Bandung'],
            ['id' => 3205, 'kode' => '3205', 'provinsi_id' => 32, 'nama' => 'Kabupaten Garut'],
            ['id' => 3206, 'kode' => '3206', 'provinsi_id' => 32, 'nama' => 'Kabupaten Tasikmalaya'],
            ['id' => 3207, 'kode' => '3207', 'provinsi_id' => 32, 'nama' => 'Kabupaten Ciamis'],
            ['id' => 3208, 'kode' => '3208', 'provinsi_id' => 32, 'nama' => 'Kabupaten Kuningan'],
            ['id' => 3209, 'kode' => '3209', 'provinsi_id' => 32, 'nama' => 'Kabupaten Cirebon'],
            ['id' => 3210, 'kode' => '3210', 'provinsi_id' => 32, 'nama' => 'Kabupaten Majalengka'],
            ['id' => 3211, 'kode' => '3211', 'provinsi_id' => 32, 'nama' => 'Kabupaten Sumedang'],
            ['id' => 3212, 'kode' => '3212', 'provinsi_id' => 32, 'nama' => 'Kabupaten Indramayu'],
            ['id' => 3213, 'kode' => '3213', 'provinsi_id' => 32, 'nama' => 'Kabupaten Subang'],
            ['id' => 3214, 'kode' => '3214', 'provinsi_id' => 32, 'nama' => 'Kabupaten Purwakarta'],
            ['id' => 3215, 'kode' => '3215', 'provinsi_id' => 32, 'nama' => 'Kabupaten Karawang'],
            ['id' => 3216, 'kode' => '3216', 'provinsi_id' => 32, 'nama' => 'Kabupaten Bekasi'],
            ['id' => 3217, 'kode' => '3217', 'provinsi_id' => 32, 'nama' => 'Kabupaten Bandung Barat'],
            ['id' => 3218, 'kode' => '3218', 'provinsi_id' => 32, 'nama' => 'Kabupaten Pangandaran'],
            ['id' => 3271, 'kode' => '3271', 'provinsi_id' => 32, 'nama' => 'Kota Bogor'],
            ['id' => 3272, 'kode' => '3272', 'provinsi_id' => 32, 'nama' => 'Kota Sukabumi'],
            ['id' => 3273, 'kode' => '3273', 'provinsi_id' => 32, 'nama' => 'Kota Bandung'],
            ['id' => 3274, 'kode' => '3274', 'provinsi_id' => 32, 'nama' => 'Kota Cirebon'],
            ['id' => 3275, 'kode' => '3275', 'provinsi_id' => 32, 'nama' => 'Kota Bekasi'],
            ['id' => 3276, 'kode' => '3276', 'provinsi_id' => 32, 'nama' => 'Kota Depok'],
            ['id' => 3277, 'kode' => '3277', 'provinsi_id' => 32, 'nama' => 'Kota Cimahi'],
            ['id' => 3278, 'kode' => '3278', 'provinsi_id' => 32, 'nama' => 'Kota Tasikmalaya'],
            ['id' => 3279, 'kode' => '3279', 'provinsi_id' => 32, 'nama' => 'Kota Banjar'],
            ['id' => 3301, 'kode' => '3301', 'provinsi_id' => 33, 'nama' => 'Kabupaten Cilacap'],
            ['id' => 3302, 'kode' => '3302', 'provinsi_id' => 33, 'nama' => 'Kabupaten Banyumas'],
            ['id' => 3303, 'kode' => '3303', 'provinsi_id' => 33, 'nama' => 'Kabupaten Purbalingga'],
            ['id' => 3304, 'kode' => '3304', 'provinsi_id' => 33, 'nama' => 'Kabupaten Banjarnegara'],
            ['id' => 3305, 'kode' => '3305', 'provinsi_id' => 33, 'nama' => 'Kabupaten Kebumen'],
            ['id' => 3306, 'kode' => '3306', 'provinsi_id' => 33, 'nama' => 'Kabupaten Purworejo'],
            ['id' => 3307, 'kode' => '3307', 'provinsi_id' => 33, 'nama' => 'Kabupaten Wonosobo'],
            ['id' => 3308, 'kode' => '3308', 'provinsi_id' => 33, 'nama' => 'Kabupaten Magelang'],
            ['id' => 3309, 'kode' => '3309', 'provinsi_id' => 33, 'nama' => 'Kabupaten Boyolali'],
            ['id' => 3310, 'kode' => '3310', 'provinsi_id' => 33, 'nama' => 'Kabupaten Klaten'],
            ['id' => 3311, 'kode' => '3311', 'provinsi_id' => 33, 'nama' => 'Kabupaten Sukoharjo'],
            ['id' => 3312, 'kode' => '3312', 'provinsi_id' => 33, 'nama' => 'Kabupaten Wonogiri'],
            ['id' => 3313, 'kode' => '3313', 'provinsi_id' => 33, 'nama' => 'Kabupaten Karanganyar'],
            ['id' => 3314, 'kode' => '3314', 'provinsi_id' => 33, 'nama' => 'Kabupaten Sragen'],
            ['id' => 3315, 'kode' => '3315', 'provinsi_id' => 33, 'nama' => 'Kabupaten Grobogan'],
            ['id' => 3316, 'kode' => '3316', 'provinsi_id' => 33, 'nama' => 'Kabupaten Blora'],
            ['id' => 3317, 'kode' => '3317', 'provinsi_id' => 33, 'nama' => 'Kabupaten Rembang'],
            ['id' => 3318, 'kode' => '3318', 'provinsi_id' => 33, 'nama' => 'Kabupaten Pati'],
            ['id' => 3319, 'kode' => '3319', 'provinsi_id' => 33, 'nama' => 'Kabupaten Kudus'],
            ['id' => 3320, 'kode' => '3320', 'provinsi_id' => 33, 'nama' => 'Kabupaten Jepara'],
            ['id' => 3321, 'kode' => '3321', 'provinsi_id' => 33, 'nama' => 'Kabupaten Demak'],
            ['id' => 3322, 'kode' => '3322', 'provinsi_id' => 33, 'nama' => 'Kabupaten Semarang'],
            ['id' => 3323, 'kode' => '3323', 'provinsi_id' => 33, 'nama' => 'Kabupaten Temanggung'],
            ['id' => 3324, 'kode' => '3324', 'provinsi_id' => 33, 'nama' => 'Kabupaten Kendal'],
            ['id' => 3325, 'kode' => '3325', 'provinsi_id' => 33, 'nama' => 'Kabupaten Batang'],
            ['id' => 3326, 'kode' => '3326', 'provinsi_id' => 33, 'nama' => 'Kabupaten Pekalongan'],
            ['id' => 3327, 'kode' => '3327', 'provinsi_id' => 33, 'nama' => 'Kabupaten Pemalang'],
            ['id' => 3328, 'kode' => '3328', 'provinsi_id' => 33, 'nama' => 'Kabupaten Tegal'],
            ['id' => 3329, 'kode' => '3329', 'provinsi_id' => 33, 'nama' => 'Kabupaten Brebes'],
            ['id' => 3371, 'kode' => '3371', 'provinsi_id' => 33, 'nama' => 'Kota Magelang'],
            ['id' => 3372, 'kode' => '3372', 'provinsi_id' => 33, 'nama' => 'Kota Surakarta'],
            ['id' => 3373, 'kode' => '3373', 'provinsi_id' => 33, 'nama' => 'Kota Salatiga'],
            ['id' => 3374, 'kode' => '3374', 'provinsi_id' => 33, 'nama' => 'Kota Semarang'],
            ['id' => 3375, 'kode' => '3375', 'provinsi_id' => 33, 'nama' => 'Kota Pekalongan'],
            ['id' => 3376, 'kode' => '3376', 'provinsi_id' => 33, 'nama' => 'Kota Tegal'],
            ['id' => 3401, 'kode' => '3401', 'provinsi_id' => 34, 'nama' => 'Kabupaten Kulon Progo'],
            ['id' => 3402, 'kode' => '3402', 'provinsi_id' => 34, 'nama' => 'Kabupaten Bantul'],
            ['id' => 3403, 'kode' => '3403', 'provinsi_id' => 34, 'nama' => 'Kabupaten Gunungkidul'],
            ['id' => 3404, 'kode' => '3404', 'provinsi_id' => 34, 'nama' => 'Kabupaten Sleman'],
            ['id' => 3471, 'kode' => '3471', 'provinsi_id' => 34, 'nama' => 'Kota Yogyakarta'],
            ['id' => 3501, 'kode' => '3501', 'provinsi_id' => 35, 'nama' => 'Kabupaten Pacitan'],
            ['id' => 3502, 'kode' => '3502', 'provinsi_id' => 35, 'nama' => 'Kabupaten Ponorogo'],
            ['id' => 3503, 'kode' => '3503', 'provinsi_id' => 35, 'nama' => 'Kabupaten Trenggalek'],
            ['id' => 3504, 'kode' => '3504', 'provinsi_id' => 35, 'nama' => 'Kabupaten Tulungagung'],
            ['id' => 3505, 'kode' => '3505', 'provinsi_id' => 35, 'nama' => 'Kabupaten Blitar'],
            ['id' => 3506, 'kode' => '3506', 'provinsi_id' => 35, 'nama' => 'Kabupaten Kediri'],
            ['id' => 3507, 'kode' => '3507', 'provinsi_id' => 35, 'nama' => 'Kabupaten Malang'],
            ['id' => 3508, 'kode' => '3508', 'provinsi_id' => 35, 'nama' => 'Kabupaten Lumajang'],
            ['id' => 3509, 'kode' => '3509', 'provinsi_id' => 35, 'nama' => 'Kabupaten Jember'],
            ['id' => 3510, 'kode' => '3510', 'provinsi_id' => 35, 'nama' => 'Kabupaten Banyuwangi'],
            ['id' => 3511, 'kode' => '3511', 'provinsi_id' => 35, 'nama' => 'Kabupaten Bondowoso'],
            ['id' => 3512, 'kode' => '3512', 'provinsi_id' => 35, 'nama' => 'Kabupaten Situbondo'],
            ['id' => 3513, 'kode' => '3513', 'provinsi_id' => 35, 'nama' => 'Kabupaten Probolinggo'],
            ['id' => 3514, 'kode' => '3514', 'provinsi_id' => 35, 'nama' => 'Kabupaten Pasuruan'],
            ['id' => 3515, 'kode' => '3515', 'provinsi_id' => 35, 'nama' => 'Kabupaten Sidoarjo'],
            ['id' => 3516, 'kode' => '3516', 'provinsi_id' => 35, 'nama' => 'Kabupaten Mojokerto'],
            ['id' => 3517, 'kode' => '3517', 'provinsi_id' => 35, 'nama' => 'Kabupaten Jombang'],
            ['id' => 3518, 'kode' => '3518', 'provinsi_id' => 35, 'nama' => 'Kabupaten Nganjuk'],
            ['id' => 3519, 'kode' => '3519', 'provinsi_id' => 35, 'nama' => 'Kabupaten Madiun'],
            ['id' => 3520, 'kode' => '3520', 'provinsi_id' => 35, 'nama' => 'Kabupaten Magetan'],
            ['id' => 3521, 'kode' => '3521', 'provinsi_id' => 35, 'nama' => 'Kabupaten Ngawi'],
            ['id' => 3522, 'kode' => '3522', 'provinsi_id' => 35, 'nama' => 'Kabupaten Bojonegoro'],
            ['id' => 3523, 'kode' => '3523', 'provinsi_id' => 35, 'nama' => 'Kabupaten Tuban'],
            ['id' => 3524, 'kode' => '3524', 'provinsi_id' => 35, 'nama' => 'Kabupaten Lamongan'],
            ['id' => 3525, 'kode' => '3525', 'provinsi_id' => 35, 'nama' => 'Kabupaten Gresik'],
            ['id' => 3526, 'kode' => '3526', 'provinsi_id' => 35, 'nama' => 'Kabupaten Bangkalan'],
            ['id' => 3527, 'kode' => '3527', 'provinsi_id' => 35, 'nama' => 'Kabupaten Sampang'],
            ['id' => 3528, 'kode' => '3528', 'provinsi_id' => 35, 'nama' => 'Kabupaten Pamekasan'],
            ['id' => 3529, 'kode' => '3529', 'provinsi_id' => 35, 'nama' => 'Kabupaten Sumenep'],
            ['id' => 3571, 'kode' => '3571', 'provinsi_id' => 35, 'nama' => 'Kota Kediri'],
            ['id' => 3572, 'kode' => '3572', 'provinsi_id' => 35, 'nama' => 'Kota Blitar'],
            ['id' => 3573, 'kode' => '3573', 'provinsi_id' => 35, 'nama' => 'Kota Malang'],
            ['id' => 3574, 'kode' => '3574', 'provinsi_id' => 35, 'nama' => 'Kota Probolinggo'],
            ['id' => 3575, 'kode' => '3575', 'provinsi_id' => 35, 'nama' => 'Kota Pasuruan'],
            ['id' => 3576, 'kode' => '3576', 'provinsi_id' => 35, 'nama' => 'Kota Mojokerto'],
            ['id' => 3577, 'kode' => '3577', 'provinsi_id' => 35, 'nama' => 'Kota Madiun'],
            ['id' => 3578, 'kode' => '3578', 'provinsi_id' => 35, 'nama' => 'Kota Surabaya'],
            ['id' => 3579, 'kode' => '3579', 'provinsi_id' => 35, 'nama' => 'Kota Batu'],
            ['id' => 3601, 'kode' => '3601', 'provinsi_id' => 36, 'nama' => 'Kabupaten Pandeglang'],
            ['id' => 3602, 'kode' => '3602', 'provinsi_id' => 36, 'nama' => 'Kabupaten Lebak'],
            ['id' => 3603, 'kode' => '3603', 'provinsi_id' => 36, 'nama' => 'Kabupaten Tangerang'],
            ['id' => 3604, 'kode' => '3604', 'provinsi_id' => 36, 'nama' => 'Kabupaten Serang'],
            ['id' => 3671, 'kode' => '3671', 'provinsi_id' => 36, 'nama' => 'Kota Tangerang'],
            ['id' => 3672, 'kode' => '3672', 'provinsi_id' => 36, 'nama' => 'Kota Cilegon'],
            ['id' => 3673, 'kode' => '3673', 'provinsi_id' => 36, 'nama' => 'Kota Serang'],
            ['id' => 3674, 'kode' => '3674', 'provinsi_id' => 36, 'nama' => 'Kota Tangerang Selatan'],
            ['id' => 5101, 'kode' => '5101', 'provinsi_id' => 51, 'nama' => 'Kabupaten Jembrana'],
            ['id' => 5102, 'kode' => '5102', 'provinsi_id' => 51, 'nama' => 'Kabupaten Tabanan'],
            ['id' => 5103, 'kode' => '5103', 'provinsi_id' => 51, 'nama' => 'Kabupaten Badung'],
            ['id' => 5104, 'kode' => '5104', 'provinsi_id' => 51, 'nama' => 'Kabupaten Gianyar'],
            ['id' => 5105, 'kode' => '5105', 'provinsi_id' => 51, 'nama' => 'Kabupaten Klungkung'],
            ['id' => 5106, 'kode' => '5106', 'provinsi_id' => 51, 'nama' => 'Kabupaten Bangli'],
            ['id' => 5107, 'kode' => '5107', 'provinsi_id' => 51, 'nama' => 'Kabupaten Karangasem'],
            ['id' => 5108, 'kode' => '5108', 'provinsi_id' => 51, 'nama' => 'Kabupaten Buleleng'],
            ['id' => 5171, 'kode' => '5171', 'provinsi_id' => 51, 'nama' => 'Kota Denpasar'],
            ['id' => 5201, 'kode' => '5201', 'provinsi_id' => 52, 'nama' => 'Kabupaten Lombok Barat'],
            ['id' => 5202, 'kode' => '5202', 'provinsi_id' => 52, 'nama' => 'Kabupaten Lombok Tengah'],
            ['id' => 5203, 'kode' => '5203', 'provinsi_id' => 52, 'nama' => 'Kabupaten Lombok Timur'],
            ['id' => 5204, 'kode' => '5204', 'provinsi_id' => 52, 'nama' => 'Kabupaten Sumbawa'],
            ['id' => 5205, 'kode' => '5205', 'provinsi_id' => 52, 'nama' => 'Kabupaten Dompu'],
            ['id' => 5206, 'kode' => '5206', 'provinsi_id' => 52, 'nama' => 'Kabupaten Bima'],
            ['id' => 5207, 'kode' => '5207', 'provinsi_id' => 52, 'nama' => 'Kabupaten Sumbawa Barat'],
            ['id' => 5208, 'kode' => '5208', 'provinsi_id' => 52, 'nama' => 'Kabupaten Lombok Utara'],
            ['id' => 5271, 'kode' => '5271', 'provinsi_id' => 52, 'nama' => 'Kota Mataram'],
            ['id' => 5272, 'kode' => '5272', 'provinsi_id' => 52, 'nama' => 'Kota Bima'],
            ['id' => 5301, 'kode' => '5301', 'provinsi_id' => 53, 'nama' => 'Kabupaten Kupang'],
            ['id' => 5302, 'kode' => '5302', 'provinsi_id' => 53, 'nama' => 'Kabupaten Timor Tengah Selatan'],
            ['id' => 5303, 'kode' => '5303', 'provinsi_id' => 53, 'nama' => 'Kabupaten Timor Tengah Utara'],
            ['id' => 5304, 'kode' => '5304', 'provinsi_id' => 53, 'nama' => 'Kabupaten Belu'],
            ['id' => 5305, 'kode' => '5305', 'provinsi_id' => 53, 'nama' => 'Kabupaten Alor'],
            ['id' => 5306, 'kode' => '5306', 'provinsi_id' => 53, 'nama' => 'Kabupaten Flores Timur'],
            ['id' => 5307, 'kode' => '5307', 'provinsi_id' => 53, 'nama' => 'Kabupaten Sikka'],
            ['id' => 5308, 'kode' => '5308', 'provinsi_id' => 53, 'nama' => 'Kabupaten Ende'],
            ['id' => 5309, 'kode' => '5309', 'provinsi_id' => 53, 'nama' => 'Kabupaten Ngada'],
            ['id' => 5310, 'kode' => '5310', 'provinsi_id' => 53, 'nama' => 'Kabupaten Manggarai'],
            ['id' => 5311, 'kode' => '5311', 'provinsi_id' => 53, 'nama' => 'Kabupaten Sumba Timur'],
            ['id' => 5312, 'kode' => '5312', 'provinsi_id' => 53, 'nama' => 'Kabupaten Sumba Barat'],
            ['id' => 5313, 'kode' => '5313', 'provinsi_id' => 53, 'nama' => 'Kabupaten Lembata'],
            ['id' => 5314, 'kode' => '5314', 'provinsi_id' => 53, 'nama' => 'Kabupaten Rote Ndao'],
            ['id' => 5315, 'kode' => '5315', 'provinsi_id' => 53, 'nama' => 'Kabupaten Manggarai Barat'],
            ['id' => 5316, 'kode' => '5316', 'provinsi_id' => 53, 'nama' => 'Kabupaten Nagekeo'],
            ['id' => 5317, 'kode' => '5317', 'provinsi_id' => 53, 'nama' => 'Kabupaten Sumba Tengah'],
            ['id' => 5318, 'kode' => '5318', 'provinsi_id' => 53, 'nama' => 'Kabupaten Sumba Barat Daya'],
            ['id' => 5319, 'kode' => '5319', 'provinsi_id' => 53, 'nama' => 'Kabupaten Manggarai Timur'],
            ['id' => 5320, 'kode' => '5320', 'provinsi_id' => 53, 'nama' => 'Kabupaten Sabu Raijua'],
            ['id' => 5321, 'kode' => '5321', 'provinsi_id' => 53, 'nama' => 'Kabupaten Malaka'],
            ['id' => 5371, 'kode' => '5371', 'provinsi_id' => 53, 'nama' => 'Kota Kupang'],
            ['id' => 6101, 'kode' => '6101', 'provinsi_id' => 61, 'nama' => 'Kabupaten Sambas'],
            ['id' => 6102, 'kode' => '6102', 'provinsi_id' => 61, 'nama' => 'Kabupaten Mempawah'],
            ['id' => 6103, 'kode' => '6103', 'provinsi_id' => 61, 'nama' => 'Kabupaten Sanggau'],
            ['id' => 6104, 'kode' => '6104', 'provinsi_id' => 61, 'nama' => 'Kabupaten Ketapang'],
            ['id' => 6105, 'kode' => '6105', 'provinsi_id' => 61, 'nama' => 'Kabupaten Sintang'],
            ['id' => 6106, 'kode' => '6106', 'provinsi_id' => 61, 'nama' => 'Kabupaten Kapuas Hulu'],
            ['id' => 6107, 'kode' => '6107', 'provinsi_id' => 61, 'nama' => 'Kabupaten Bengkayang'],
            ['id' => 6108, 'kode' => '6108', 'provinsi_id' => 61, 'nama' => 'Kabupaten Landak'],
            ['id' => 6109, 'kode' => '6109', 'provinsi_id' => 61, 'nama' => 'Kabupaten Sekadau'],
            ['id' => 6110, 'kode' => '6110', 'provinsi_id' => 61, 'nama' => 'Kabupaten Melawi'],
            ['id' => 6111, 'kode' => '6111', 'provinsi_id' => 61, 'nama' => 'Kabupaten Kayong Utara'],
            ['id' => 6112, 'kode' => '6112', 'provinsi_id' => 61, 'nama' => 'Kabupaten Kubu Raya'],
            ['id' => 6171, 'kode' => '6171', 'provinsi_id' => 61, 'nama' => 'Kota Pontianak'],
            ['id' => 6172, 'kode' => '6172', 'provinsi_id' => 61, 'nama' => 'Kota Singkawang'],
            ['id' => 6201, 'kode' => '6201', 'provinsi_id' => 62, 'nama' => 'Kabupaten Kotawaringin Barat'],
            ['id' => 6202, 'kode' => '6202', 'provinsi_id' => 62, 'nama' => 'Kabupaten Kotawaringin Timur'],
            ['id' => 6203, 'kode' => '6203', 'provinsi_id' => 62, 'nama' => 'Kabupaten Kapuas'],
            ['id' => 6204, 'kode' => '6204', 'provinsi_id' => 62, 'nama' => 'Kabupaten Barito Selatan'],
            ['id' => 6205, 'kode' => '6205', 'provinsi_id' => 62, 'nama' => 'Kabupaten Barito Utara'],
            ['id' => 6206, 'kode' => '6206', 'provinsi_id' => 62, 'nama' => 'Kabupaten Katingan'],
            ['id' => 6207, 'kode' => '6207', 'provinsi_id' => 62, 'nama' => 'Kabupaten Seruyan'],
            ['id' => 6208, 'kode' => '6208', 'provinsi_id' => 62, 'nama' => 'Kabupaten Sukamara'],
            ['id' => 6209, 'kode' => '6209', 'provinsi_id' => 62, 'nama' => 'Kabupaten Lamandau'],
            ['id' => 6210, 'kode' => '6210', 'provinsi_id' => 62, 'nama' => 'Kabupaten Gunung Mas'],
            ['id' => 6211, 'kode' => '6211', 'provinsi_id' => 62, 'nama' => 'Kabupaten Pulang Pisau'],
            ['id' => 6212, 'kode' => '6212', 'provinsi_id' => 62, 'nama' => 'Kabupaten Murung Raya'],
            ['id' => 6213, 'kode' => '6213', 'provinsi_id' => 62, 'nama' => 'Kabupaten Barito Timur'],
            ['id' => 6271, 'kode' => '6271', 'provinsi_id' => 62, 'nama' => 'Kota Palangkaraya'],
            ['id' => 6301, 'kode' => '6301', 'provinsi_id' => 63, 'nama' => 'Kabupaten Tanah Laut'],
            ['id' => 6302, 'kode' => '6302', 'provinsi_id' => 63, 'nama' => 'Kabupaten Kotabaru'],
            ['id' => 6303, 'kode' => '6303', 'provinsi_id' => 63, 'nama' => 'Kabupaten Banjar'],
            ['id' => 6304, 'kode' => '6304', 'provinsi_id' => 63, 'nama' => 'Kabupaten Barito Kuala'],
            ['id' => 6305, 'kode' => '6305', 'provinsi_id' => 63, 'nama' => 'Kabupaten Tapin'],
            ['id' => 6306, 'kode' => '6306', 'provinsi_id' => 63, 'nama' => 'Kabupaten Hulu Sungai Selatan'],
            ['id' => 6307, 'kode' => '6307', 'provinsi_id' => 63, 'nama' => 'Kabupaten Hulu Sungai Tengah'],
            ['id' => 6308, 'kode' => '6308', 'provinsi_id' => 63, 'nama' => 'Kabupaten Hulu Sungai Utara'],
            ['id' => 6309, 'kode' => '6309', 'provinsi_id' => 63, 'nama' => 'Kabupaten Tabalong'],
            ['id' => 6310, 'kode' => '6310', 'provinsi_id' => 63, 'nama' => 'Kabupaten Tanah Bumbu'],
            ['id' => 6311, 'kode' => '6311', 'provinsi_id' => 63, 'nama' => 'Kabupaten Balangan'],
            ['id' => 6371, 'kode' => '6371', 'provinsi_id' => 63, 'nama' => 'Kota Banjarmasin'],
            ['id' => 6372, 'kode' => '6372', 'provinsi_id' => 63, 'nama' => 'Kota Banjarbaru'],
            ['id' => 6401, 'kode' => '6401', 'provinsi_id' => 64, 'nama' => 'Kabupaten Paser'],
            ['id' => 6402, 'kode' => '6402', 'provinsi_id' => 64, 'nama' => 'Kabupaten Kutai Kartanegara'],
            ['id' => 6403, 'kode' => '6403', 'provinsi_id' => 64, 'nama' => 'Kabupaten Berau'],
            ['id' => 6407, 'kode' => '6407', 'provinsi_id' => 64, 'nama' => 'Kabupaten Kutai Barat'],
            ['id' => 6408, 'kode' => '6408', 'provinsi_id' => 64, 'nama' => 'Kabupaten Kutai Timur'],
            ['id' => 6409, 'kode' => '6409', 'provinsi_id' => 64, 'nama' => 'Kabupaten Penajam Paser Utara'],
            ['id' => 6411, 'kode' => '6411', 'provinsi_id' => 64, 'nama' => 'Kabupaten Mahakam Ulu'],
            ['id' => 6471, 'kode' => '6471', 'provinsi_id' => 64, 'nama' => 'Kota Balikpapan'],
            ['id' => 6472, 'kode' => '6472', 'provinsi_id' => 64, 'nama' => 'Kota Samarinda'],
            ['id' => 6474, 'kode' => '6474', 'provinsi_id' => 64, 'nama' => 'Kota Bontang'],
            ['id' => 6501, 'kode' => '6501', 'provinsi_id' => 65, 'nama' => 'Kabupaten Bulungan'],
            ['id' => 6502, 'kode' => '6502', 'provinsi_id' => 65, 'nama' => 'Kabupaten Malinau'],
            ['id' => 6503, 'kode' => '6503', 'provinsi_id' => 65, 'nama' => 'Kabupaten Nunukan'],
            ['id' => 6504, 'kode' => '6504', 'provinsi_id' => 65, 'nama' => 'Kabupaten Tana Tidung'],
            ['id' => 6571, 'kode' => '6571', 'provinsi_id' => 65, 'nama' => 'Kota Tarakan'],
            ['id' => 7101, 'kode' => '7101', 'provinsi_id' => 71, 'nama' => 'Kabupaten Bolaang Mongondow'],
            ['id' => 7102, 'kode' => '7102', 'provinsi_id' => 71, 'nama' => 'Kabupaten Minahasa'],
            ['id' => 7103, 'kode' => '7103', 'provinsi_id' => 71, 'nama' => 'Kabupaten Kepulauan Sangihe'],
            ['id' => 7104, 'kode' => '7104', 'provinsi_id' => 71, 'nama' => 'Kabupaten Kepulauan Talaud'],
            ['id' => 7105, 'kode' => '7105', 'provinsi_id' => 71, 'nama' => 'Kabupaten Minahasa Selatan'],
            ['id' => 7106, 'kode' => '7106', 'provinsi_id' => 71, 'nama' => 'Kabupaten Minahasa Utara'],
            ['id' => 7107, 'kode' => '7107', 'provinsi_id' => 71, 'nama' => 'Kabupaten Minahasa Tenggara'],
            ['id' => 7108, 'kode' => '7108', 'provinsi_id' => 71, 'nama' => 'Kabupaten Bolaang Mongondow Utar'],
            ['id' => 7109, 'kode' => '7109', 'provinsi_id' => 71, 'nama' => 'Kabupaten Kep. Siau Tagulandang '],
            ['id' => 7110, 'kode' => '7110', 'provinsi_id' => 71, 'nama' => 'Kabupaten Bolaang Mongondow Timu'],
            ['id' => 7111, 'kode' => '7111', 'provinsi_id' => 71, 'nama' => 'Kabupaten Bolaang Mongondow Sela'],
            ['id' => 7171, 'kode' => '7171', 'provinsi_id' => 71, 'nama' => 'Kota Manado'],
            ['id' => 7172, 'kode' => '7172', 'provinsi_id' => 71, 'nama' => 'Kota Bitung'],
            ['id' => 7173, 'kode' => '7173', 'provinsi_id' => 71, 'nama' => 'Kota Tomohon'],
            ['id' => 7174, 'kode' => '7174', 'provinsi_id' => 71, 'nama' => 'Kota Kotamobagu'],
            ['id' => 7201, 'kode' => '7201', 'provinsi_id' => 72, 'nama' => 'Kabupaten Banggai'],
            ['id' => 7202, 'kode' => '7202', 'provinsi_id' => 72, 'nama' => 'Kabupaten Poso'],
            ['id' => 7203, 'kode' => '7203', 'provinsi_id' => 72, 'nama' => 'Kabupaten Donggala'],
            ['id' => 7204, 'kode' => '7204', 'provinsi_id' => 72, 'nama' => 'Kabupaten Toli-Toli'],
            ['id' => 7205, 'kode' => '7205', 'provinsi_id' => 72, 'nama' => 'Kabupaten Buol'],
            ['id' => 7206, 'kode' => '7206', 'provinsi_id' => 72, 'nama' => 'Kabupaten Morowali'],
            ['id' => 7207, 'kode' => '7207', 'provinsi_id' => 72, 'nama' => 'Kabupaten Banggai Kepulauan'],
            ['id' => 7208, 'kode' => '7208', 'provinsi_id' => 72, 'nama' => 'Kabupaten Parigi Moutong'],
            ['id' => 7209, 'kode' => '7209', 'provinsi_id' => 72, 'nama' => 'Kabupaten Tojo Una Una'],
            ['id' => 7210, 'kode' => '7210', 'provinsi_id' => 72, 'nama' => 'Kabupaten Sigi'],
            ['id' => 7211, 'kode' => '7211', 'provinsi_id' => 72, 'nama' => 'Kabupaten Banggai Laut'],
            ['id' => 7212, 'kode' => '7212', 'provinsi_id' => 72, 'nama' => 'Kabupaten Morowali Utara'],
            ['id' => 7271, 'kode' => '7271', 'provinsi_id' => 72, 'nama' => 'Kota Palu'],
            ['id' => 7301, 'kode' => '7301', 'provinsi_id' => 73, 'nama' => 'Kabupaten Kepulauan Selayar'],
            ['id' => 7302, 'kode' => '7302', 'provinsi_id' => 73, 'nama' => 'Kabupaten Bulukumba'],
            ['id' => 7303, 'kode' => '7303', 'provinsi_id' => 73, 'nama' => 'Kabupaten Bantaeng'],
            ['id' => 7304, 'kode' => '7304', 'provinsi_id' => 73, 'nama' => 'Kabupaten Jeneponto'],
            ['id' => 7305, 'kode' => '7305', 'provinsi_id' => 73, 'nama' => 'Kabupaten Takalar'],
            ['id' => 7306, 'kode' => '7306', 'provinsi_id' => 73, 'nama' => 'Kabupaten Gowa'],
            ['id' => 7307, 'kode' => '7307', 'provinsi_id' => 73, 'nama' => 'Kabupaten Sinjai'],
            ['id' => 7308, 'kode' => '7308', 'provinsi_id' => 73, 'nama' => 'Kabupaten Bone'],
            ['id' => 7309, 'kode' => '7309', 'provinsi_id' => 73, 'nama' => 'Kabupaten Maros'],
            ['id' => 7310, 'kode' => '7310', 'provinsi_id' => 73, 'nama' => 'Kabupaten Pangkajene dan Kepulau'],
            ['id' => 7311, 'kode' => '7311', 'provinsi_id' => 73, 'nama' => 'Kabupaten Barru'],
            ['id' => 7312, 'kode' => '7312', 'provinsi_id' => 73, 'nama' => 'Kabupaten Soppeng'],
            ['id' => 7313, 'kode' => '7313', 'provinsi_id' => 73, 'nama' => 'Kabupaten Wajo'],
            ['id' => 7314, 'kode' => '7314', 'provinsi_id' => 73, 'nama' => 'Kabupaten Sidenreng Rappang'],
            ['id' => 7315, 'kode' => '7315', 'provinsi_id' => 73, 'nama' => 'Kabupaten Pinrang'],
            ['id' => 7316, 'kode' => '7316', 'provinsi_id' => 73, 'nama' => 'Kabupaten Enrekang'],
            ['id' => 7317, 'kode' => '7317', 'provinsi_id' => 73, 'nama' => 'Kabupaten Luwu'],
            ['id' => 7318, 'kode' => '7318', 'provinsi_id' => 73, 'nama' => 'Kabupaten Tana Toraja'],
            ['id' => 7322, 'kode' => '7322', 'provinsi_id' => 73, 'nama' => 'Kabupaten Luwu Utara'],
            ['id' => 7324, 'kode' => '7324', 'provinsi_id' => 73, 'nama' => 'Kabupaten Luwu Timur'],
            ['id' => 7326, 'kode' => '7326', 'provinsi_id' => 73, 'nama' => 'Kabupaten Toraja Utara'],
            ['id' => 7371, 'kode' => '7371', 'provinsi_id' => 73, 'nama' => 'Kota Makassar'],
            ['id' => 7372, 'kode' => '7372', 'provinsi_id' => 73, 'nama' => 'Kota Parepare'],
            ['id' => 7373, 'kode' => '7373', 'provinsi_id' => 73, 'nama' => 'Kota Palopo'],
            ['id' => 7401, 'kode' => '7401', 'provinsi_id' => 74, 'nama' => 'Kabupaten Kolaka'],
            ['id' => 7402, 'kode' => '7402', 'provinsi_id' => 74, 'nama' => 'Kabupaten Konawe'],
            ['id' => 7403, 'kode' => '7403', 'provinsi_id' => 74, 'nama' => 'Kabupaten Muna'],
            ['id' => 7404, 'kode' => '7404', 'provinsi_id' => 74, 'nama' => 'Kabupaten Buton'],
            ['id' => 7405, 'kode' => '7405', 'provinsi_id' => 74, 'nama' => 'Kabupaten Konawe Selatan'],
            ['id' => 7406, 'kode' => '7406', 'provinsi_id' => 74, 'nama' => 'Kabupaten Bombana'],
            ['id' => 7407, 'kode' => '7407', 'provinsi_id' => 74, 'nama' => 'Kabupaten Wakatobi'],
            ['id' => 7408, 'kode' => '7408', 'provinsi_id' => 74, 'nama' => 'Kabupaten Kolaka Utara'],
            ['id' => 7409, 'kode' => '7409', 'provinsi_id' => 74, 'nama' => 'Kabupaten Konawe Utara'],
            ['id' => 7410, 'kode' => '7410', 'provinsi_id' => 74, 'nama' => 'Kabupaten Buton Utara'],
            ['id' => 7411, 'kode' => '7411', 'provinsi_id' => 74, 'nama' => 'Kabupaten Kolaka Timur'],
            ['id' => 7412, 'kode' => '7412', 'provinsi_id' => 74, 'nama' => 'Kabupaten Konawe Kepulauan'],
            ['id' => 7413, 'kode' => '7413', 'provinsi_id' => 74, 'nama' => 'Kabupaten Muna Barat'],
            ['id' => 7414, 'kode' => '7414', 'provinsi_id' => 74, 'nama' => 'Kabupaten Buton Tengah'],
            ['id' => 7415, 'kode' => '7415', 'provinsi_id' => 74, 'nama' => 'Kabupaten Buton Selatan'],
            ['id' => 7471, 'kode' => '7471', 'provinsi_id' => 74, 'nama' => 'Kota Kendari'],
            ['id' => 7472, 'kode' => '7472', 'provinsi_id' => 74, 'nama' => 'Kota Bau Bau'],
            ['id' => 7501, 'kode' => '7501', 'provinsi_id' => 75, 'nama' => 'Kabupaten Gorontalo'],
            ['id' => 7502, 'kode' => '7502', 'provinsi_id' => 75, 'nama' => 'Kabupaten Boalemo'],
            ['id' => 7503, 'kode' => '7503', 'provinsi_id' => 75, 'nama' => 'Kabupaten Bone Bolango'],
            ['id' => 7504, 'kode' => '7504', 'provinsi_id' => 75, 'nama' => 'Kabupaten Pohuwato'],
            ['id' => 7505, 'kode' => '7505', 'provinsi_id' => 75, 'nama' => 'Kabupaten Gorontalo Utara'],
            ['id' => 7571, 'kode' => '7571', 'provinsi_id' => 75, 'nama' => 'Kota Gorontalo'],
            ['id' => 7601, 'kode' => '7601', 'provinsi_id' => 76, 'nama' => 'Kabupaten Pasangkayu'],
            ['id' => 7602, 'kode' => '7602', 'provinsi_id' => 76, 'nama' => 'Kabupaten Mamuju'],
            ['id' => 7603, 'kode' => '7603', 'provinsi_id' => 76, 'nama' => 'Kabupaten Mamasa'],
            ['id' => 7604, 'kode' => '7604', 'provinsi_id' => 76, 'nama' => 'Kabupaten Polewali Mandar'],
            ['id' => 7605, 'kode' => '7605', 'provinsi_id' => 76, 'nama' => 'Kabupaten Majene'],
            ['id' => 7606, 'kode' => '7606', 'provinsi_id' => 76, 'nama' => 'Kabupaten Mamuju Tengah'],
            ['id' => 8101, 'kode' => '8101', 'provinsi_id' => 81, 'nama' => 'Kabupaten Maluku Tengah'],
            ['id' => 8102, 'kode' => '8102', 'provinsi_id' => 81, 'nama' => 'Kabupaten Maluku Tenggara'],
            ['id' => 8103, 'kode' => '8103', 'provinsi_id' => 81, 'nama' => 'Kabupaten Kepulauan Tanimbar'],
            ['id' => 8104, 'kode' => '8104', 'provinsi_id' => 81, 'nama' => 'Kabupaten Buru'],
            ['id' => 8105, 'kode' => '8105', 'provinsi_id' => 81, 'nama' => 'Kabupaten Seram Bagian Timur'],
            ['id' => 8106, 'kode' => '8106', 'provinsi_id' => 81, 'nama' => 'Kabupaten Seram Bagian Barat'],
            ['id' => 8107, 'kode' => '8107', 'provinsi_id' => 81, 'nama' => 'Kabupaten Kepulauan Aru'],
            ['id' => 8108, 'kode' => '8108', 'provinsi_id' => 81, 'nama' => 'Kabupaten Maluku Barat Daya'],
            ['id' => 8109, 'kode' => '8109', 'provinsi_id' => 81, 'nama' => 'Kabupaten Buru Selatan'],
            ['id' => 8171, 'kode' => '8171', 'provinsi_id' => 81, 'nama' => 'Kota Ambon'],
            ['id' => 8172, 'kode' => '8172', 'provinsi_id' => 81, 'nama' => 'Kota Tual'],
            ['id' => 8201, 'kode' => '8201', 'provinsi_id' => 82, 'nama' => 'Kabupaten Halmahera Barat'],
            ['id' => 8202, 'kode' => '8202', 'provinsi_id' => 82, 'nama' => 'Kabupaten Halmahera Tengah'],
            ['id' => 8203, 'kode' => '8203', 'provinsi_id' => 82, 'nama' => 'Kabupaten Halmahera Utara'],
            ['id' => 8204, 'kode' => '8204', 'provinsi_id' => 82, 'nama' => 'Kabupaten Halmahera Selatan'],
            ['id' => 8205, 'kode' => '8205', 'provinsi_id' => 82, 'nama' => 'Kabupaten Kepulauan Sula'],
            ['id' => 8206, 'kode' => '8206', 'provinsi_id' => 82, 'nama' => 'Kabupaten Halmahera Timur'],
            ['id' => 8207, 'kode' => '8207', 'provinsi_id' => 82, 'nama' => 'Kabupaten Pulau Morotai'],
            ['id' => 8208, 'kode' => '8208', 'provinsi_id' => 82, 'nama' => 'Kabupaten Pulau Taliabu'],
            ['id' => 8271, 'kode' => '8271', 'provinsi_id' => 82, 'nama' => 'Kota Ternate'],
            ['id' => 8272, 'kode' => '8272', 'provinsi_id' => 82, 'nama' => 'Kota Tidore Kepulauan'],
            ['id' => 9103, 'kode' => '9103', 'provinsi_id' => 91, 'nama' => 'Kabupaten Jayapura'],
            ['id' => 9105, 'kode' => '9105', 'provinsi_id' => 91, 'nama' => 'Kabupaten Kepulauan Yapen'],
            ['id' => 9106, 'kode' => '9106', 'provinsi_id' => 91, 'nama' => 'Kabupaten Biak Numfor'],
            ['id' => 9110, 'kode' => '9110', 'provinsi_id' => 91, 'nama' => 'Kabupaten Sarmi'],
            ['id' => 9111, 'kode' => '9111', 'provinsi_id' => 91, 'nama' => 'Kabupaten Keerom'],
            ['id' => 9115, 'kode' => '9115', 'provinsi_id' => 91, 'nama' => 'Kabupaten Waropen'],
            ['id' => 9119, 'kode' => '9119', 'provinsi_id' => 91, 'nama' => 'Kabupaten Supiori'],
            ['id' => 9120, 'kode' => '9120', 'provinsi_id' => 91, 'nama' => 'Kabupaten Mamberamo Raya'],
            ['id' => 9171, 'kode' => '9171', 'provinsi_id' => 91, 'nama' => 'Kota Jayapura'],
            ['id' => 9202, 'kode' => '9202', 'provinsi_id' => 92, 'nama' => 'Kabupaten Manokwari'],
            ['id' => 9203, 'kode' => '9203', 'provinsi_id' => 92, 'nama' => 'Kabupaten Fak Fak'],
            ['id' => 9206, 'kode' => '9206', 'provinsi_id' => 92, 'nama' => 'Kabupaten Teluk Bintuni'],
            ['id' => 9207, 'kode' => '9207', 'provinsi_id' => 92, 'nama' => 'Kabupaten Teluk Wondama'],
            ['id' => 9208, 'kode' => '9208', 'provinsi_id' => 92, 'nama' => 'Kabupaten Kaimana'],
            ['id' => 9211, 'kode' => '9211', 'provinsi_id' => 92, 'nama' => 'Kabupaten Manokwari Selatan'],
            ['id' => 9212, 'kode' => '9212', 'provinsi_id' => 92, 'nama' => 'Kabupaten Pegunungan Arfak'],
            ['id' => 9301, 'kode' => '9301', 'provinsi_id' => 93, 'nama' => 'Kabupaten Merauke'],
            ['id' => 9302, 'kode' => '9302', 'provinsi_id' => 93, 'nama' => 'Kabupaten Boven Digoel'],
            ['id' => 9303, 'kode' => '9303', 'provinsi_id' => 93, 'nama' => 'Kabupaten Mappi'],
            ['id' => 9304, 'kode' => '9304', 'provinsi_id' => 93, 'nama' => 'Kabupaten Asmat'],
            ['id' => 9401, 'kode' => '9401', 'provinsi_id' => 94, 'nama' => 'Kabupaten Nabire'],
            ['id' => 9402, 'kode' => '9402', 'provinsi_id' => 94, 'nama' => 'Kabupaten Puncak Jaya'],
            ['id' => 9403, 'kode' => '9403', 'provinsi_id' => 94, 'nama' => 'Kabupaten Paniai'],
            ['id' => 9404, 'kode' => '9404', 'provinsi_id' => 94, 'nama' => 'Kabupaten Mimika'],
            ['id' => 9405, 'kode' => '9405', 'provinsi_id' => 94, 'nama' => 'Kabupaten Puncak'],
            ['id' => 9406, 'kode' => '9406', 'provinsi_id' => 94, 'nama' => 'Kabupaten Dogiyai'],
            ['id' => 9407, 'kode' => '9407', 'provinsi_id' => 94, 'nama' => 'Kabupaten Intan Jaya'],
            ['id' => 9408, 'kode' => '9408', 'provinsi_id' => 94, 'nama' => 'Kabupaten Deiyai'],
            ['id' => 9501, 'kode' => '9501', 'provinsi_id' => 95, 'nama' => 'Kabupaten Jayawijaya'],
            ['id' => 9502, 'kode' => '9502', 'provinsi_id' => 95, 'nama' => 'Kabupaten Pegunungan Bintang'],
            ['id' => 9503, 'kode' => '9503', 'provinsi_id' => 95, 'nama' => 'Kabupaten Yahukimo'],
            ['id' => 9504, 'kode' => '9504', 'provinsi_id' => 95, 'nama' => 'Kabupaten Tolikara'],
            ['id' => 9505, 'kode' => '9505', 'provinsi_id' => 95, 'nama' => 'Kabupaten Mamberamo Tengah'],
            ['id' => 9506, 'kode' => '9506', 'provinsi_id' => 95, 'nama' => 'Kabupaten Yalimo'],
            ['id' => 9507, 'kode' => '9507', 'provinsi_id' => 95, 'nama' => 'Kabupaten Lanny Jaya'],
            ['id' => 9508, 'kode' => '9508', 'provinsi_id' => 95, 'nama' => 'Kabupaten Nduga'],
            ['id' => 9601, 'kode' => '9601', 'provinsi_id' => 96, 'nama' => 'Kabupaten Sorong'],
            ['id' => 9602, 'kode' => '9602', 'provinsi_id' => 96, 'nama' => 'Kabupaten Sorong Selatan'],
            ['id' => 9603, 'kode' => '9603', 'provinsi_id' => 96, 'nama' => 'Kabupaten Raja Ampat'],
            ['id' => 9604, 'kode' => '9604', 'provinsi_id' => 96, 'nama' => 'Kabupaten Tambrauw'],
            ['id' => 9605, 'kode' => '9605', 'provinsi_id' => 96, 'nama' => 'Kabupaten Maybrat'],
            ['id' => 9671, 'kode' => '9671', 'provinsi_id' => 96, 'nama' => 'Kota Sorong'],
        ];
    }

    /**
     * Peta id kabupaten ke namanya, untuk pencarian cepat.
     *
     * @return array<int, string>
     */
    public static function petaKabupaten(): array
    {
        return array_column(self::kabupaten(), 'nama', 'id');
    }

    /**
     * Peta id provinsi ke namanya.
     *
     * @return array<int, string>
     */
    public static function petaProvinsi(): array
    {
        return array_column(self::provinsi(), 'nama', 'id');
    }

    /**
     * Nama satu kabupaten, atau null bila idnya tidak dikenal.
     *
     * Mengembalikan null, bukan tanda hubung maupun string kosong: pemanggilnya
     * yang menentukan cara menampilkan nilai yang belum terisi, dan pembeda
     * antara belum diisi dan tidak ditemukan tetap terbaca di sini.
     *
     * @param  int|null  $id  Nilai id kabupaten
     */
    public static function namaKabupaten(?int $id): ?string
    {
        return $id === null ? null : (self::petaKabupaten()[$id] ?? null);
    }

    /**
     * Daftar kabupaten siap pakai untuk komponen `x-sim.pilih-cari`.
     *
     * Menyertakan nama provinsi sebagai keterangan, sebab nama kabupaten TIDAK
     * unik secara nasional. Tanpa keterangan itu petugas tidak dapat membedakan
     * Kabupaten Kupang dari Kota Kupang, dan pilihan yang keliru tidak akan
     * pernah memerahkan apa pun.
     *
     * Diurutkan menurut nama agar penelusuran manual tetap mungkin ketika
     * petugas tidak ingat ejaan persisnya.
     *
     * @return array<int, array{id: int, nama: string, provinsi: string}>
     */
    public static function opsiKabupaten(): array
    {
        $provinsi = self::petaProvinsi();

        $opsi = array_map(fn (array $k) => [
            'id' => $k['id'],
            'nama' => $k['nama'],
            'provinsi' => $provinsi[$k['provinsi_id']] ?? '',
        ], self::kabupaten());

        usort($opsi, fn ($a, $b) => strcmp($a['nama'], $b['nama']));

        return $opsi;
    }
}
